apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: task-manager
  labels:
    app: task-manager
spec:
  type: LoadBalancer
  selector:
    app: task-manager
  ports:
    - port: 80
      targetPort: 80

